---
#
# Ansible managed
#
repository:
  description: Install the latest stable version of kubectl on your system.
  homepage: https://buluma.github.io/
  topics: kubectl, ansible, molecule, tox, playbook
